version: "3.9"
services:

  rdf:
    image: openlink/virtuoso-opensource-7:latest
    volumes:
      - type: bind
        source: ./tests
        target: /initdb.d
    ports:
      - 8888:8890

  # Feel free to (un)comment below services to spare memory and CPU
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200