version: "3.9"
services:

  rdf:
    image: openlink/virtuoso-opensource-7:latest
    volumes:
      - type: bind
        source: ./tests
        target: /initdb.d
    ports:
      - 8888:8890

  # Feel free to (un)comment below services to spare memory and CPU
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_USER: user
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
