version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  rdf:
    image: openlink/virtuoso-opensource-7:latest
    volumes:
      - type: bind
        source: ./tests
        target: /initdb.d
    ports:
      - 8888:8890