version: '3.9'
services:
  rdf:
    image: openlink/virtuoso-opensource-7:latest
    volumes:
      - type: bind
        source: ../test
        target: /initdb.d
    ports:
      - 8888:8890

  mysql:
    image: bitnami/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_USER: user
      MYSQL_DATABASE: mysql_labelstore
    ports:
      - '3306:3306'

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: mariadb_labelstore
    ports:
      - '3307:3306'
