version: '3.9'
services:
  rdf:
    image: openlink/virtuoso-opensource-7:latest
    volumes:
      - type: bind
        source: ../test
        target: /initdb.d
    ports:
      - 8888:8890

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
