version: '3.9'
services:
  rdf:
    image: openlink/virtuoso-opensource-7:latest
    volumes:
      - type: bind
        source: ../test
        target: /initdb.d
    ports:
      - 8888:8890

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
