apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: SPARQL_ADDRESS
            value: {{ .Values.sparqlConfig.sparqlAddress | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.apiConfig.logLevel }}
          - name: PORT
            value: {{ .Values.apiConfig.port | default 80 | quote }}
          {{- if ne (.Values.sparqlConfig.includedGraphs | join " ") "" }}
          - name: INCLUDED_GRAPHS
            value: {{ .Values.sparqlConfig.includedGraphs | join " " | quote }}
          {{- end }}
          - name: API_PREFIX
            value: {{ .Values.apiConfig.prefix | default "api" }}
          {{- if ne (.Values.sparqlConfig.exclusions.classes | join " ") "" }}
          - name: EXCLUDED_CLASSES
            value: {{ .Values.sparqlConfig.exclusions.classes | join " " | quote }}
          {{- end }}

          {{- if ne (.Values.sparqlConfig.exclusions.namespaces | join " ") "" }}
          - name: EXCLUDED_NAMESPACES
            value: {{ .Values.sparqlConfig.exclusions.namespaces | join " " | quote }}
          {{- end }}
          {{- if .Values.labelStore.enabled }}
          - name: LABEL_STORE_URL
            valueFrom: 
              secretKeyRef:
                name: {{ include "api.fullname" . }}-labelstore-secret
                key: uri
          - name: LABEL_STORE_TOKEN
            valueFrom: 
              secretKeyRef:
                name: {{ include "api.fullname" . }}-labelstore-secret
                key: token
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{.Values.image.registry | default "ghcr.io"}}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.apiConfig.port | default 80 }}
              protocol: TCP
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: {{ join "/" (list (include "api.prefix" .) .Values.probes.readiness.path ) | clean }}
              port: http
            initialDelaySeconds: 15
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: {{ join "/" (list (include "api.prefix" .) .Values.probes.readiness.path ) | clean }}
              port: http
            initialDelaySeconds: 15
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
