{{- if .Values.labelStore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-labelstore-secret
  labels: {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
    uri: {{ .Values.labelStore.config.url | b64enc | quote }}
    token: {{ .Values.labelStore.config.token | b64enc | quote }}
{{- end }}