# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: ghcr.io
  repository: woodenmaiden/relfinderreformedapi
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: 'latest'

# Please refer to https://github.com/WoodenMaiden/RelfinderReformedAPI/blob/master/README.md#env-variables
sparqlConfig:
  sparqlAddress: https://someurl
  includedGraphs:
    []
    # - http://graph1
    # - http://graph2
    # - http://graph3
  exclusions:
    # v Not fully implemented yet
    classes: []
    namespaces: []

apiConfig:
  port: 8080
  logLevel: error
  prefix: /api

labelStore:
  enabled: false
  config:
    url: '' # your connection url
    token: '' # if you need an auth token

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

ingress:
  enabled: true
  className: ''
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # cert-manager.io/issuer: dontForgetFoEnableValues.ingress.tls!

  # Points to the frontend service
  # the api is served on /api on the same ingress
  hostname: rfr.local
  path: /
  pathType: ImplementationSpecific
  extraPaths: 
    []
    # - path: /api
    #   backend:
    #     serviceName: ssl-redirect
    #     servicePort: use-annotation
  tls: false

  extraTls:
  # - hosts:
  #     - nginx.local
  #   secretName: nginx.local-tls
  

egress:
  enabled: false
  rules:
    - to:
        - ipBlock:
          cidr: 0.0.0.0/0

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

probes:
  readiness:
    enabled: true
    path: /health
  liveness:
    enabled: true
    path: /health

nodeSelector: {}

tolerations: []

affinity: {}

frontend:
  enable: true

  # in this frontend object you can define every values you
  # would define on https://artifacthub.io/packages/helm/bitnami/nginx
  image:
    registry: ghcr.io
    repository: woodenmaiden/relfinderreformedfront
    pullPolicy: IfNotPresent
    tag: 'latest'
  extraEnvVars: 
    - name: DISABLE_REDIRECT
      value: "yes"
  ingress:
    enabled: false