# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/woodenmaiden/relfinderreformedapi
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 'latest'

# Please refer to https://github.com/WoodenMaiden/RelfinderReformedAPI/blob/master/README.md#env-variables
sparqlConfig:
  sparqlAddress: https://someurl
  includedGraphs:
    []
    # - http://graph1
    # - http://graph2
    # - http://graph3
  exclusions:
    # v Not fully implemented yet
    classes: []
    namespaces: []

apiConfig:
  port: 80
  logLevel: error

labelStore:
  enabled: false
  config:
    url: '' # your connection url
    token: '' # if you need an auth token

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

ingress:
  enabled: true
  className: ''
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: api.127.0.0.1.sslip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

egress:
  enabled: false
  rules:
    - to:
        - ipBlock:
          cidr: 0.0.0.0/0

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

probes:
  readiness:
    enabled: true
    path: /health
  liveness:
    enabled: true
    path: /health

nodeSelector: {}

tolerations: []

affinity: {}
