name: Push to dev environment

on:
  push:
    branches-ignore:
      - master
      - main
      - '*cd*'
      - '*ci*' # Ignore CICD branches
    paths:
      - charts/**
      - src/**
      - test/**
      - Dockerfile
      - typings/**
      - docker-entrypoint.sh

# This workflow will build a docker container, publish it to our private registry
# tagged as latest and with latest commit hash (shortened)
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Get short commit hash
        id: variables
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          config-inline: |
            [registry."harbor.dev.agrold.org"]
              http = true
              insecure = true

      - name: Insecure Docker Repository
        run: |
          cat /etc/docker/daemon.json | jq '.["insecure-registries"] += ["harbor.dev.agrold.org"]' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: 'Login to private registry at: ${{ vars.DOCKER_REGISTRY_HOST }}'
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ vars.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: |
            GIT_COMMIT=${{ steps.variables.outputs.sha_short }}
          allow: security.insecure # Activated because docker does not like self signed certificates
          push: true
          tags: ${{ vars.DOCKER_REGISTRY_HOST }}/rfr/relfinderreformedapi:${{ steps.variables.outputs.sha_short }},${{ vars.DOCKER_REGISTRY_HOST }}/rfr/relfinderreformedapi:latest
