name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  set_vars:
    runs-on: ubuntu-latest
    outputs:
      no_v: ${{ steps.set_version.outputs.no_v }}

    steps:
      - name: Set Versions
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            core.setOutput('no_v', no_v)

  publish_docker:
    runs-on: ubuntu-latest
    needs: set_vars

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            GIT_VERSION=${{ needs.set_vars.outputs.no_v }}
          push: true
          tags: ghcr.io/woodenmaiden/relfinderreformedapi:${{ needs.set_vars.outputs.no_v }},ghcr.io/woodenmaiden/relfinderreformedapi:latest

  helm_release:
    permissions:
      contents: write
    needs: set_vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          mark_as_latest: true
          skip_existing: true
          charts_dir: charts
