name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  set_vars:
    runs-on: ubuntu-latest
    outputs:
      no_v: ${{ steps.set_version.outputs.no_v }}

    steps:
      - name: Set Versions
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            core.setOutput('no_v', no_v)

  publish_docker:
    runs-on: ubuntu-latest
    needs: set_vars

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            GIT_VERSION=${{ needs.set_vars.outputs.no_v }}
          push: true
          tags: ghcr.io/woodenmaiden/relfinderreformedapi:${{ needs.set_vars.outputs.no_v }},ghcr.io/woodenmaiden/relfinderreformedapi:latest

  helm_release:
    permissions:
      contents: write
    needs: set_vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          app_version: ${{ needs.set_vars.outputs.no_v }}
          charts_dir: charts

  release:
    needs: [helm_release, publish_docker]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Changelog from Conventional Commits
        id: changelog
        uses: requarks/changelog-action@v1.10.2
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          excludeScopes: cicd,ci,cd,
          writeToFile: false
          useGitmojis: true
          includeInvalidCommits: true

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}